version: "3.8"

services:
  backend:
    image: snesh111/real_talk-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    image: snesh111/real_talk-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
